services:
  node:
    build:
      context: ../
      args:
        PROJECT: gitopia
        PROJECT_BIN: gitopiad
        PROJECT_DIR: .gitopia
        VERSION: v6.0.0
        REPOSITORY: https://github.com/gitopia/gitopia
        BUILD_CMD: make build
        BINARY_PATH: build/gitopiad
    ports:
      - '26656:26656'
      - '26657:26657'
      - '1317:1317'
    volumes:
      - ./node-data:/root/.gitopia
